spring:
  application:
    name: ProductsService
  profiles.active: dev
  sql.init.mode: always
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:h2:mem:productsdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 8080


products.openapi:
    dev-url: "http://localhost:9090"
    prod-url: "https://localhost:8443"

app.jwt.secret: SECRET-KEY-VALUE

---
spring:
  config.activate.on-profile: dev

server:
  port: 9090
  error:
     include-message: always
     include-binding-errors: always
     include-stacktrace: on-param
     include-exception: false


#debug: true
logging:
  path: /var/tmp/
  file: /var/tmp/mylog.log
  level:
    root: INFO


---
spring:
  config.activate.on-profile: prod

server:
  servlet.contextPath: /api/v1
  port: 8443
  ssl:
    key-store: "c:/Course/workspace/spring5/vault_1.p12"
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: products_service
